### ISSUE TITLE
incomplete data

### ISSUE THREAD

**Issue by saeednm** [listeomid/listeomid.org#19]
برای استان آذربایجان شرقی نمایندگان مجلس خبرگان لیست نشده است

**Comment by listeomid** [comment]
ممنون از تذکر. لیست رو به روز کردیم. تا چند دقیقه سایت هم به روز میشه. اگر بعد از ۱۵ دقیقه هنوز مشکلی در لیست بود،‌ لطفا دوباره این تیکت رو باز کنید

**Comment by saeednm** [comment]
هنوز آپدیت نشده

**Comment by saeednm** [comment]
درست شد. سپاس

**Comment by saeednm** [comment]
صفحه عادی در مرورگر کش شده و با بستن و باز کردن درست نشد. اما با باز کردن صفحه 
incognito  
 درست نشون میده
