### ISSUE TITLE
پیشنهاد مشخص کردن برگزیدگان در لیست

### ISSUE THREAD

**Issue by MortezaHosseini** [listeomid/listeomid.org#29]
تشکر می‌کنم از اینکه کار خوبی ارائه کردید و همه‌چیز رو به بهترین شکل انجام دادید. از استفاده از پروتکل امن گرفته تا اپن سورس کردن و گرافیک تمیز ودر عین حال زیبا :)
پیشنهادی که دارم اینه که بر طبق اخبار رسمی ، نه اخبار غیر قابل اعتنا رنگ برگزیدگان هر حوزه رو سبز :) کنید.

**Comment by listeomid** [comment]
<div dir="rtl">سلام و تشکر از حمایتتون. سایت با نتایج به روز شده.</div>
